# Generated by Django 2.2.4 on 2019-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentFirstName', models.CharField(max_length=50)),
                ('StudentMiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('StudentLastName', models.CharField(blank=True, max_length=50, null=True)),
                ('FathersName', models.CharField(max_length=50)),
                ('RollNumber', models.CharField(max_length=50)),
                ('RegistrationID', models.IntegerField()),
                ('studentemailid', models.CharField(blank=True, max_length=50, null=True)),
                ('studentphonenumber', models.CharField(blank=True, max_length=13, null=True)),
                ('homephonenumber', models.CharField(blank=True, max_length=13, null=True)),
                ('aadharnumber', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
