# Generated by Django 2.2.4 on 2019-08-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jamaat',
            fields=[
                ('jamaatid', models.AutoField(primary_key=True, serialize=False)),
                ('jamaatname', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField()),
                ('createuserid', models.IntegerField()),
                ('updateuserid', models.IntegerField()),
            ],
            options={
                'db_table': 'Jamaat',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=50)),
                ('SubjectNameUrdu', models.CharField(max_length=50)),
                ('SubjectDescription', models.CharField(max_length=300)),
                ('MaxMark', models.IntegerField()),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField()),
                ('createuserid', models.IntegerField()),
                ('updateuserid', models.IntegerField()),
                ('jamaatid', models.ForeignKey(db_column='jamaatid', on_delete=django.db.models.deletion.DO_NOTHING, to='jamatSubject.Jamaat')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
